name: flutter_provider_sample
description: A sample Flutter project for Provider
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Tools
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  freezed_annotation:
  provider: ^6.0.0

  # UI
  cached_network_image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansCJKjp
      fonts:
        - asset: assets/fonts/NotoSansCJKjp-Regular.ttf
        - asset: assets/fonts/NotoSansCJKjp-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansCJKjp-Bold.ttf
          weight: 700
