name: flutter_provider_sample
description: A sample Flutter project for Provider
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
